version: '3.8'

services:
  base_image:
    build:
      context: ..
      dockerfile: docker/Dockerfile.base
    image: base

  controller:
    build:
      context: ..
      dockerfile: docker/Dockerfile.controller
    depends_on:
      - base_image
    restart: always
    ports:
      - "21001:21001"

  modelworker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.model_worker
    depends_on:
      - base_image
      - controller
    restart: always
    ports:
      - "21002:21002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  webserver:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web_server
    depends_on:
      - base_image
      - modelworker
    restart: always
    ports:
      - "7860:7860"
      #  - "8000:8000"

